{% set name = "herbie-data" %}
{% set version = "2026.1.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 96ab0e2325dc43234f7425777fe8af960ac54d8bec4acc8ffbb7fafd13691181

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - PYTHONIOENCODING=utf8

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs

  run:
    - cartopy >=0.25.0
    - cfgrib >=0.9.15.1
    - curl
    #- eccodes >=2.45.0
    - matplotlib-base >=3.10.0
    - metpy >=1.7.1
    - numpy >=1.26.4
    - pandas >=2.2.3
    - pyproj >=3.7
    - python >={{ python_min }}
    #- python-eccodes
    - requests >=2.23.3
    - scikit-learn >=1.8.0
    #- wgrib2  # [linux]
    - xarray >=2025.1.1

test:
  commands:
    - pip check
  imports:
    - herbie
    - herbie.models
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/blaylockbk/Herbie
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Download numerical weather prediction GRIB2 model data.
  description: |
    Herbie is a python package that downloads recent and archived numerical weather
    prediction (NWP) model output from different cloud archive sources. Its most
    popular capability is to download HRRR model data. NWP data in GRIB2 format
    can be read with xarray+cfgrib. Much of this data is made available through the
    NOAA Open Data Dissemination (NODD) Program (formerly the Big Data Program)
    which has made weather data more accessible than ever before.
  doc_url: https://herbie.readthedocs.io/
  dev_url: https://github.com/blaylockbk/Herbie

extra:
  recipe-maintainers:
    - blaylockbk
