{% set name = "herbie-data" %}
{% set version = "2024.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3e69309baadbb3c18453b02ececfc533a810d324836a0409084b8a91a4c842e2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - PYTHONIOENCODING=utf8

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools
    - setuptools_scm

  run:
    - cartopy
    - cfgrib >=0.9.10.1
    - curl
    - matplotlib-base >=3.5.0
    - metpy
    - numpy
    - pandas
    - pygrib
    - pyproj
    - python >=3.9
    - requests
    - scikit-learn
    - toml
    #- wgrib2  # [linux]
    - xarray

test:
  commands:
    - pip check
  imports:
    - herbie
    - herbie.models
  requires:
    - pip

about:
  home: https://github.com/blaylockbk/Herbie
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Download numerical weather prediction GRIB2 model data.
  description: |
    Herbie is a python package that downloads recent and archived numerical weather
    prediction (NWP) model output from different cloud archive sources. Its most
    popular capability is to download HRRR model data. NWP data in GRIB2 format
    can be read with xarray+cfgrib. Much of this data is made available through the
    NOAA Open Data Dissemination (NODD) Program (formerly the Big Data Program)
    which has made weather data more accessible than ever before.
  doc_url: https://herbie.readthedocs.io/
  dev_url: https://github.com/blaylockbk/Herbie

extra:
  recipe-maintainers:
    - blaylockbk
