{% set name = "herbie-data" %}
{% set version = "2025.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8489256135adc255bb7b8e4470ede04640a481b54a42940baf23760368b8b725

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - PYTHONIOENCODING=utf8

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm

  run:
    - cartopy
    - cfgrib >=0.9.15
    - curl
    - matplotlib-base >=3.8.0
    - metpy
    - numpy >=1.24
    - pandas >=2.1
    - pyproj >=3.7
    - python >={{ python_min }}
    - requests
    - scikit-learn
    - toml
    #- wgrib2  # [linux]
    - xarray >=2025.1.1

test:
  commands:
    - pip check
  imports:
    - herbie
    - herbie.models
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/blaylockbk/Herbie
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Download numerical weather prediction GRIB2 model data.
  description: |
    Herbie is a python package that downloads recent and archived numerical weather
    prediction (NWP) model output from different cloud archive sources. Its most
    popular capability is to download HRRR model data. NWP data in GRIB2 format
    can be read with xarray+cfgrib. Much of this data is made available through the
    NOAA Open Data Dissemination (NODD) Program (formerly the Big Data Program)
    which has made weather data more accessible than ever before.
  doc_url: https://herbie.readthedocs.io/
  dev_url: https://github.com/blaylockbk/Herbie

extra:
  recipe-maintainers:
    - blaylockbk
